### ISSUE TITLE
PyTorch version incompatible with OSCER's CUDA driver

### ISSUE THREAD

**Issue by luketerry0** [JayRothenberger/OUAI-HPC-Demo#1]
When running the job, a long stack trace is printed, with the following important line:

```
[W CUDAFunctions.cpp:108] Warning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (function operator())
```

I did not have this issue before OSCER's scheduled maintenance on 9/4/24, so it seems that the CUDA driver has been changed to something incompatible with PyTorch on this conda environment.

The full stacktrace:

```
wandb: Currently logged in as: luketerry0 (luketerry0-university-of-oklahoma). Use `wandb login --relogin` to force relogin
[2024-09-04 21:15:28,813] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2024-09-04 21:15:28,813] torch.distributed.run: [WARNING] 
[2024-09-04 21:15:28,813] torch.distributed.run: [WARNING] *****************************************
[2024-09-04 21:15:28,813] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-09-04 21:15:28,813] torch.distributed.run: [WARNING] *****************************************
[2024-09-04 21:15:29,299] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2024-09-04 21:15:29,299] torch.distributed.run: [WARNING] 
[2024-09-04 21:15:29,299] torch.distributed.run: [WARNING] *****************************************
[2024-09-04 21:15:29,299] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-09-04 21:15:29,299] torch.distributed.run: [WARNING] *****************************************
[W CUDAFunctions.cpp:108] Warning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (function operator())
Traceback (most recent call last):
  File "/home/luketerry/OUAI-HPC-Demo/main.py", line 305, in <module>
    main()
  File "/home/luketerry/OUAI-HPC-Demo/main.py", line 291, in main
    setup()
  File "/home/luketerry/OUAI-HPC-Demo/main.py", line 152, in setup
    dist.init_process_group("nccl", rank=int(os.environ['RANK']), world_size=int(os.environ['WORLD_SIZE']))
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1279, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
[2024-09-04 21:15:35,063] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 13290 closing signal SIGTERM
[2024-09-04 21:15:35,095] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 13291) of binary: /home/jroth/.conda/envs/mct/bin/python
Traceback (most recent call last):
  File "/home/luketerry/mambaforge/envs/mct/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-04_21:15:35
  host      : c301.oscer.ou.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 13291)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: c301: task 0: Exited with exit code 1
[W socket.cpp:663] [c10d] The client socket has failed to connect to [c301.oscer.ou.edu]:60845 (errno: 113 - No route to host).
[W socket.cpp:663] [c10d] The client socket has failed to connect to [c301.oscer.ou.edu]:60845 (errno: 113 - No route to host).
[2024-09-04 21:15:39,413] torch.distributed.elastic.rendezvous.dynamic_rendezvous: [WARNING] The node 'c302.oscer.ou.edu_30326_0' has failed to send a keep-alive heartbeat to the rendezvous '17254' due to an error of type RendezvousConnectionError.
[2024-09-04 21:15:40,070] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 30336 closing signal SIGTERM
[2024-09-04 21:15:40,070] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 30337 closing signal SIGTERM
[2024-09-04 21:15:40,105] torch.distributed.elastic.rendezvous.dynamic_rendezvous: [WARNING] The node 'c302.oscer.ou.edu_30326_0' has failed to shutdown the rendezvous '17254' due to an error of type RendezvousConnectionError.
Traceback (most recent call last):
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 113, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
RuntimeError: Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luketerry/mambaforge/envs/mct/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 909, in _invoke_run
    num_nodes_waiting = rdzv_handler.num_nodes_waiting()
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1083, in num_nodes_waiting
    self._state_holder.sync()
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 409, in sync
    get_response = self._backend.get_state()
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 73, in get_state
    base64_state: bytes = self._call_store("get", self._key)
  File "/home/jroth/.conda/envs/mct/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 115, in _call_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
srun: error: c302: task 1: Exited with exit code 1

```

**Comment by JayRothenberger** [comment]
I cleared the package cache and reinstalled all of the packages in my environment.  I think they must have updated the operating system or changed some hardware configuration on the nodes and the compiled packages stopped working.  It seems to work now.  Hopefully this was a one time issue.  Feel free to raise another if it happens again.
